### ISSUE TITLE
error message by install 

### ISSUE THREAD

**Issue by BogusCurry** [ReinerNippes/selfhosted_on_docker#1]
Hello ;D
At first, sorry for my bad englisch, I comes from germany ;D
So, ok, I have install over your Script the apps, but at last comes this message over the top 
https://paste.md-5.net/exaxelohuj.sql

My system ist Ubuntu 18.04, is the error my fail or is that a bug ?

Have a nice Day ;D
Bogus

**Comment by ReinerNippes** [comment]
Lauscht da schon ein Webserver oder ein anderer Dienst auf Port 443?

(Someone else listening on port 443?)

**Comment by BogusCurry** [comment]
Ja hab Apache installiert, der wird da wohl lauschen .. Kann ich den Port im Script ändern oder muss er bleiben ?

Yes, is run a apache ;D Can I change the port in the Script is the must have ?

**Comment by ReinerNippes** [comment]
Juppp. Here we go:
https://github.com/ReinerNippes/selfhosted_on_docker/blob/272c34ed98e46edc46ed98b209241eea04eac455/roles/docker_base/tasks/traefik.yml#L41

Wenn du jinja2 und ansible verstanden hast, kannst du auch eine {{ traefik_ssl_port_variable }} nehmen. ;-)

**Comment by BogusCurry** [comment]
ne soweit bin noch nicht ;D

Danke für deine schnelle Antwort ;D

**Comment by BogusCurry** [comment]
Ok, konnte es nicht lassen, müsste eigentlich schon längst schlafen *gg Aber ich bekomme nun noch ein Fatal message
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "usermod: user www-data is currently used by process 26069\n", "name": "www-data", "rc": 8}

Keinen schimmer was das sein könnte ...
`
Und hab einen Fehler in der Anleitung entdeckt .. es heisst 
Prepare your OS to run the playook and install Docker on your server.

./prepare_os.sh statt sh  ... müsste da doch ein .yml hin oder ?

**Comment by BogusCurry** [comment]
Die meldung mit dem nextcloud kommt nicht mehr, hab das script /prepare_os.yml durchlaufen lassen. nun kommt aber ne andere Fehlermeldung .. aber ich gehe nun schlafen ..

**Comment by ReinerNippes** [comment]
Die Fehlermeldung bezüglich `usermod: user www-data is currently used` kommt, weil wohl bei dir einen User www-data schon gibt.
Du kannst versuchen, die beiden Tasks, die den User anlegen sollen, zu löschen oder zu disablen. An beide Tasks ein `when: false` anhängen.
https://github.com/ReinerNippes/selfhosted_on_docker/blob/64d697a6fb1f9399a3431991696699da3a494089/roles/docker_nextcloud/tasks/nextcloud.yml#L4

**Comment by BogusCurry** [comment]
Ok, werde ich mal testen ;D

**Comment by BogusCurry** [comment]
Moin ;D
So, ich komme leider nur an den WE zum basteln *gg Daher hab ich in der Woche nicht geantwortet. 

Das Script lief nun aber durch, aber ich kann die Apps nicht aufrufen. Eigentlich müsste unter http://selfhosted.magicplace.de/ das setup erscheinen, aber da kommt nur die default domainseite.

Weiss nicht, ob ich was falsch gemacht hab, aber dein Script ist super. Man muss nur mal richtig durchsteigen und die yml synthax beachten *gg

Tschöö
Bogus

**Comment by ReinerNippes** [comment]
Unter der http://selfhosted.magicplace.de/ Adresse meldet sich dein Webserver (Apache, TLS1.0). Mein Playbook hat aber eine Traefik installiert. 
Hast du mal http://selfhosted.magicplace.de:deine-port-nummer/ probiert?
Was gibt `sudo docker ps` aus?

**Comment by BogusCurry** [comment]
hmmm wieder was gelernt, dachte traefik hätte was mit statistik zu tun. mit einem cloud router hab ich nun gar ncht gerechnet.

sorry, das ich so blöde fragen stelle, hab dein per script zufall halt gefunden. was für eine port muss denn nehmen ? docker ps gibt die docker container aus

**Comment by ReinerNippes** [comment]
du hast hier
https://github.com/ReinerNippes/selfhosted_on_docker/blob/272c34ed98e46edc46ed98b209241eea04eac455/roles/docker_base/tasks/traefik.yml#L41
die eingangsports fürden traefik definiert. wenn du die ports in der firewall deines servers geöffnet hast, sollte er jetzt von außen erreichbar sein.

**Comment by BogusCurry** [comment]
Irgendwie werde ich mit deinem Script nicht warm .. denke ich werde mir nochmal docker zu gemüte führen und dann nochmal dein Script mir vornehmen ;D
Nachtrag: Mir ist aufgefallen, das die CPU von meinen Server auf gut 25% hoch ging, nachdem ich nun die Scripts gelöscht hab, ging es runter auf 6 %. Könnte aber dran liegen, das der Server nur ein kleiner VPS Server ist. Daher wird wohl mein Server ein wenig schwach auf der Brust sein für dein Script bzw. für die Apps.

Tschööö
Bogus

**Comment by ReinerNippes** [comment]
ja. das ist von den drei playbooks das anspruchsvollste. 
wenn du mehrere apps laufen lassen willst wären 4cpu und 8gb ram empfehlenswert.
