### ISSUE TITLE
Portainer not available when use PathPrefixStrip

### ISSUE THREAD

**Issue by Nickous** [ReinerNippes/selfhosted_on_docker#5]
Thank you for your great job.
A small issue:
in the file [https://github.com/ReinerNippes/selfhosted_on_docker/blob/master/roles/docker_base/tasks/portainer.yml](url)

- With your syntax:
`traefik.frontend.rule: "Host:{{ app_server_fqdn }}; PathPrefixStrip: /portainer"`
-> I've just got a blank page with label "Loading Portainer..." and that's all!! Can't connect/manage

- With subdomain :
`traefik.frontend.rule: "Host: portainer.{{ app_server_fqdn }}"`
-> My selfhosted Portainer.io is well load and works fine: I can connect and manage docker configuration.

I would prefer your syntax "<base_domain>/portainer" instead of "portainer.<base_domain>". But I'm too noob to understand what's wrong with traefik syntax.

**Comment by ReinerNippes** [comment]
I tried hart but couldn't figure out why that's not working. 

It work's with a trailing "/" like writen in the readme.

```
# portainer is a webfront end for docker host at https://{{ base_domain }}/portainer/
portainer_enabled: true
```

**Comment by Nickous** [comment]
Even with the trailing "/", doesn't work for me?!
No matter, thanks for all the attempts and community

**Comment by Nickous** [comment]
on Ubuntu 18.04, doesn't work.
I"ve just all reinstalled on Debian 10, and https://{{ base_domain }}/portainer/ is working :)
