### ISSUE TITLE
Feature Request: Adding Draw.io server (e.g. for Nextcloud integration)

### ISSUE THREAD

**Issue by janklostermann** [ReinerNippes/selfhosted_on_docker#7]
Hello Reiner,
would you mind to consider the integration of the Draw.io server docker into your selfhosted_on_docker ansibles?
That would be cool to gain a real self-hosted nextcloud installation even when using the [draw.io NC app](https://apps.nextcloud.com/apps/drawio).
The draw.io  server for docker can be found here: https://github.com/jgraph/docker-drawio
That would be awesome, as it would cover another piece from the wishlist regarding an easy-to-set-up self-hosting work environment for small projects etc.
Thanks a lot for all your work already done!

**Comment by ReinerNippes** [comment]
Ready to test.
